"""
Plan Mode Batch Reviewer
Collects plans from Claude Code instances in plan mode,
presents them for human review, and dispatches approved plans for execution.
"""

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from enum import Enum

logger = logging.getLogger(__name__)


class ReviewStatus(Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MODIFIED = "modified"


@dataclass
class Plan:
    """A plan generated by Claude Code in plan mode."""

    task_id: str
    content: str
    status: ReviewStatus = ReviewStatus.PENDING
    reviewer_notes: str = ""

    def to_dict(self) -> dict:
        return {
            "task_id": self.task_id,
            "content": self.content,
            "status": self.status.value,
            "reviewer_notes": self.reviewer_notes,
        }


class PlanReviewQueue:
    """Queue for managing plan reviews."""

    def __init__(self, plans_dir: Path):
        self.plans_dir = plans_dir
        self.plans_dir.mkdir(parents=True, exist_ok=True)

    def add_plan(self, plan: Plan):
        """Add a plan to the review queue."""
        plan_file = self.plans_dir / f"{plan.task_id}.plan.json"
        with open(plan_file, "w") as f:
            json.dump(plan.to_dict(), f, indent=2, ensure_ascii=False)
        logger.info(f"Plan queued for review: {plan.task_id}")

    def get_pending_plans(self) -> list[Plan]:
        """Get all plans pending review."""
        plans = []
        for plan_file in self.plans_dir.glob("*.plan.json"):
            with open(plan_file) as f:
                data = json.load(f)
            if data["status"] == ReviewStatus.PENDING.value:
                plans.append(
                    Plan(
                        task_id=data["task_id"],
                        content=data["content"],
                        status=ReviewStatus(data["status"]),
                        reviewer_notes=data.get("reviewer_notes", ""),
                    )
                )
        return plans

    def review_plan(
        self, task_id: str, status: ReviewStatus, notes: str = ""
    ) -> bool:
        """Update the review status of a plan."""
        plan_file = self.plans_dir / f"{task_id}.plan.json"
        if not plan_file.exists():
            logger.error(f"Plan not found: {task_id}")
            return False

        with open(plan_file) as f:
            data = json.load(f)

        data["status"] = status.value
        data["reviewer_notes"] = notes

        with open(plan_file, "w") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        logger.info(f"Plan {task_id} reviewed: {status.value}")
        return True

    def get_approved_plans(self) -> list[Plan]:
        """Get all approved plans ready for execution."""
        plans = []
        for plan_file in self.plans_dir.glob("*.plan.json"):
            with open(plan_file) as f:
                data = json.load(f)
            if data["status"] == ReviewStatus.APPROVED.value:
                plans.append(
                    Plan(
                        task_id=data["task_id"],
                        content=data["content"],
                        status=ReviewStatus.APPROVED,
                        reviewer_notes=data.get("reviewer_notes", ""),
                    )
                )
        return plans

    def remove_plan(self, task_id: str):
        """Remove a plan from the queue after execution."""
        plan_file = self.plans_dir / f"{task_id}.plan.json"
        if plan_file.exists():
            plan_file.unlink()
            logger.info(f"Plan removed: {task_id}")
